Clinic card screens
palladiumkenya/nishauri_new pull request #13
Opened 2024-12-12 00:25 UTC by vicky-ogutu

all screens for dependent's clinic-card

2024-12-12 07:03 UTC, Ogollah commented
Can you share some few screens?

2024-12-12 07:45 UTC, Ogollah reviewed
And did you fix the responsiveness, the over flows on the self screening module?

2024-12-12 07:45 UTC, Ogollah commented on lib/src/features/appointments/presentation/pages/Appointments.dart
Are we still using static data? Kindly check. We want to do away with most of the static data files.

2024-12-12 07:45 UTC, Ogollah commented on lib/src/features/chatbot/presentations/ChatScreen.dart
>                child: const Text('Yes'),
Can we have some of these texts as constatnts

2024-12-12 07:45 UTC, Ogollah commented on lib/src/features/clinic_card/data/models/health_test.dart
I think we are not using this file we can delete it.

2024-12-12 07:45 UTC, Ogollah commented on lib/src/features/clinic_card/presentation/pages/ClinicCardScreen.dart
> +
We need to think of a better way to present this.

2024-12-12 07:45 UTC, Ogollah commented on lib/src/features/clinic_card/relationship/presentation/pages/dependant_profile.dart
> +
We think on how to simplify this

2024-12-12 07:45 UTC, Ogollah commented on lib/src/features/clinic_card/relationship/widgets/medication_rship.dart
> +        _buildHospitalRow(record.facility, theme),
We were to remove the facility names from the cards.

2024-12-12 07:54 UTC, vicky-ogutu commented on lib/src/features/clinic_card/relationship/widgets/medication_rship.dart
> +        _buildHospitalRow(record.facility, theme),
https://github.com/user-attachments/assets/fde6e1e8-63ab-4639-b066-824ac06eca21

Yeah, next pr will resolve this and screen_overflows

2024-12-12 07:59 UTC, Ogollah commented on lib/src/features/clinic_card/relationship/widgets/medication_rship.dart
> +        _buildHospitalRow(record.facility, theme),
Since we are merging to master don't you think we should just fix them in this PR?

2024-12-12 08:15 UTC, vicky-ogutu commented on lib/src/features/clinic_card/relationship/widgets/medication_rship.dart
> +        _buildHospitalRow(record.facility, theme),
This can also work, so let me highlight the specific items to be resolve first

2025-01-07 05:15 UTC, Ogollah requested changes
Thank you @vicky-ogutu for good work!

2025-01-07 05:15 UTC, Ogollah commented on lib/src/utils/constants.dart
> +  static const SPACINGA = 10.0;
you might want to review this spacing

2025-01-07 05:15 UTC, Ogollah commented on lib/src/features/self_screening/presentation/pages/self_screening_menu.dart
> +                padding: const EdgeInsets.symmetric(horizontal: 8.0),
we can use Constants

2025-01-07 05:15 UTC, Ogollah commented on lib/src/features/clinic_card/relationship/widgets/condition_rship.dart
> +        // const Divider(),
We remove commented out code

2025-01-10 04:58 UTC, Ogollah commented
Is this done now? And are we not merging this to 2_0_1 first?

2025-01-10 04:58 UTC, Ogollah commented
Share latest video please.

2025-01-18 15:02 UTC, Ogollah approved these changes

2025-01-20 14:26 UTC, Ogollah reviewed
Add Screenshot and or Video

2025-01-20 14:29 UTC, Ogollah commented on lib/src/features/art/presentation/FacilityDirectory.dart
> +            subTitle: 'Some very long sub title',
You did not remove this text.

2025-01-20 14:32 UTC, vicky-ogutu commented
This is well noted, Thanks for this..

On Mon, Jan 20, 2025 at 5:29 PM Ogollah ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In lib/src/features/art/presentation/FacilityDirectory.dart
> <https://github.com/palladiumkenya/nishauri_new/pull/13#discussion_r1922488147>
> :
>
> >            CustomAppBar(
>              title: "Facility Directory 🏥",
> +            subTitle: 'Some very long sub title',
>
> You did not remove this text.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/palladiumkenya/nishauri_new/pull/13#pullrequestreview-2562535221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEOPVAFVFWE3BFTHNVBXJT2LUB5PAVCNFSM6AAAAABTOUFZ2SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNRSGUZTKMRSGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-27 08:20 UTC, merged